### ISSUE TITLE
Add project: Easter Dates

### ISSUE THREAD

**Issue by gavinr** [servusDei2018/awesome-catholic#3]
**Project name:** Easter Dates
**Project url:** https://easter-dates.gavinr.com/
**Project description:** Distribution of Easter per Date Across Years

**Comment by servusDei2018** [comment]
Nice work, the animation is amazing! Thank you!!

**Comment by historical-theology** [comment]
I agree, @gavinr . That looks outstanding!

Since the dating of Easter has been debated from the very beginnings of Christianity, and it is still a matter of disagreement between various Churches (most notably Eastern Orthodox and Roman Catholic) and ecclesial communities, you ought to include an obvious note in the website itself that this is about the historical dating of Easter in Rome (or some such specification). Otherwise, visitors might be confused.

God bless.

**Comment by gavinr** [comment]
@historical-theology thanks for the tip - will do so.
